# -*- mode:python -*-

Import('*')

SimObject('BaseAccelerator.py')
Source('base_accelerator.cc')
DebugFlag('ACCEL', 'Accelerator-related debug messages')

SimObject('NullAccelerator.py')
Source('null_accelerator.cc')

SimObject('DelayedNullAccelerator.py')
Source('delayed_null_accelerator.cc')
